spring:
  application:
    name: user-service

  profiles:
    active: local

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8081

#JWT configuration
jwt:
  secret: VGhpc0lzQVNlY3VyZUpXVFNlY3JldEtleUZvckhTMjU2QWxnb3JpdGhtMTIzNDU2
  expiration: 86400000
  refresh-expiration: 604800000

#AWS configuration
aws:
  access-key: YOUR_AWS_ACCESS_KEY
  secret-key: YOUR_AWS_SECRET_KEY
  region: eu-north-1
  s3:
    bucket-name: your-bucket-name


management:
  endpoints:
    web:
      exposure:
        include: health,info
